// <auto-generated />
using FinsoftERP.API.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FinsoftERP.API.Migrations.ERPContextMigrations
{
    [DbContext(typeof(ERPContext))]
    [Migration("20181219153134_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FinsoftERP.API.Models.AccountTypeSub", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnName("CODE")
                        .HasColumnType("VARCHAR(6)")
                        .HasMaxLength(6);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("CDESC")
                        .HasColumnType("VARCHAR(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Remarks")
                        .HasColumnType("VARCHAR(200)")
                        .HasMaxLength(200);

                    b.HasKey("Code");

                    b.ToTable("FIN_STAT_SUB");
                });

            modelBuilder.Entity("FinsoftERP.API.Models.ControlAccount", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnName("CODE")
                        .HasColumnType("VARCHAR(2)")
                        .HasMaxLength(2);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("CDESC")
                        .HasColumnType("VARCHAR(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Remarks")
                        .HasColumnType("VARCHAR(200)")
                        .HasMaxLength(200);

                    b.HasKey("Code");

                    b.ToTable("LD_CTRL");
                });

            modelBuilder.Entity("FinsoftERP.API.Models.GeneralAccount", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnName("CODE")
                        .HasColumnType("VARCHAR(4)")
                        .HasMaxLength(4);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("CDESC")
                        .HasColumnType("VARCHAR(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Remarks")
                        .HasColumnType("VARCHAR(200)")
                        .HasMaxLength(200);

                    b.HasKey("Code");

                    b.ToTable("LD_GEN");
                });

            modelBuilder.Entity("FinsoftERP.API.Models.SubsidiaryAccount", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnName("CODE")
                        .HasColumnType("VARCHAR(8)")
                        .HasMaxLength(8);

                    b.Property<string>("AccountTypeSubCode")
                        .IsRequired()
                        .HasColumnName("ACC_TYPE")
                        .HasColumnType("VARCHAR(6)")
                        .HasMaxLength(6);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnName("CDESC")
                        .HasColumnType("VARCHAR(100)")
                        .HasMaxLength(100);

                    b.Property<string>("Remarks")
                        .HasColumnType("VARCHAR(200)")
                        .HasMaxLength(200);

                    b.HasKey("Code");

                    b.HasIndex("AccountTypeSubCode");

                    b.ToTable("LD_MAIN");
                });

            modelBuilder.Entity("FinsoftERP.API.Models.SubsidiaryAccount", b =>
                {
                    b.HasOne("FinsoftERP.API.Models.AccountTypeSub", "AccountTypeSub")
                        .WithMany()
                        .HasForeignKey("AccountTypeSubCode")
                        .OnDelete(DeleteBehavior.Restrict);
                });
#pragma warning restore 612, 618
        }
    }
}
